### ISSUE TITLE
Export frame not working

### ISSUE THREAD

**Issue by DevKoshti07** [swimmingkiim/react-image-editor#2]
Export All Frame and Export Selected Frame are not working. Nothing happen when click on the export options.

**Comment by Prakash-orgin** [comment]
How can I use it in my project

**Comment by Prakash-orgin** [comment]
> Export All Frame and Export Selected Frame are not working. Nothing happen when click on the export options.

How can I use it in my project

**Comment by swimmingkiim** [comment]
> Export All Frame and Export Selected Frame are not working. Nothing happen when click on the export options.

Export action will not do anything if there're no frames in current file tab.

I've just tested with some sample frames and it's working fine.

If you have any other bug case, please feel free to tell me :)

<img width="1425" alt="스크린샷 2023-05-22 오후 3 49 43" src="https://github.com/swimmingkiim/react-image-editor/assets/54804279/a406ef20-0c96-48d7-9d82-fe99ff12cecc">

**Comment by swimmingkiim** [comment]
> > Export All Frame and Export Selected Frame are not working. Nothing happen when click on the export options.
> 
> How can I use it in my project

@Prakash-orgin I'll be glad to reply to you if you provide more background context :)
And I hope that you can register your question to new issue since it seems like irrelevant to this issue.

**Comment by DevKoshti07** [comment]
> > Export All Frame and Export Selected Frame are not working. Nothing happen when click on the export options.
> 
> Export action will not do anything if there're no frames in current file tab.
> 
> I've just tested with some sample frames and it's working fine.
> 
> If you have any other bug case, please feel free to tell me :)
> 
> <img alt="스크린샷 2023-05-22 오후 3 49 43" width="1425" src="https://user-images.githubusercontent.com/54804279/239825876-a406ef20-0c96-48d7-9d82-fe99ff12cecc.png">

Thank You for your reply, it's my mistake it works properly Thank you once again.

**Comment by DevKoshti07** [comment]
Can you please suggest how to edit text in frame?

**Comment by swimmingkiim** [comment]
> Can you please suggest how to edit text in frame?

After you drag and drop text on to canvas, there's two possible click action.

1. One click -> show transformer box around text
1. Double click **when the text is not selected** -> turns into edit mode and the text is now editable.

<img width="1440" alt="스크린샷 2023-05-23 오전 11 17 02" src="https://github.com/swimmingkiim/react-image-editor/assets/54804279/3b66ec8c-9c04-457b-83e2-800960c6a196">
<img width="1440" alt="스크린샷 2023-05-23 오전 11 18 15" src="https://github.com/swimmingkiim/react-image-editor/assets/54804279/b1bd75b1-23b4-4478-b671-3617712542b5">

**Comment by DevKoshti07** [comment]
> > Can you please suggest how to edit text in frame?
> 
> After you drag and drop text on to canvas, there's two possible click action.
> 
> 1. One click -> show transformer box around text
> 2. Double click **when the text is not selected** -> turns into edit mode and the text is now editable.
> 
> <img alt="스크린샷 2023-05-23 오전 11 17 02" width="1440" src="https://user-images.githubusercontent.com/54804279/240102092-3b66ec8c-9c04-457b-83e2-800960c6a196.png"> <img alt="스크린샷 2023-05-23 오전 11 18 15" width="1440" src="https://user-images.githubusercontent.com/54804279/240102106-b1bd75b1-23b4-4478-b671-3617712542b5.png">

Thank you for your reply. It Works Thank You.
