### ISSUE TITLE
Cannot find module 'react-image-editor' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Prakash-orgin** [swimmingkiim/react-image-editor#3]
When I import ImageEditor from node modules, I'm getting the following error "Cannot find module 'react-image-editor' or its corresponding type declarations."

**Comment by swimmingkiim** [comment]
> When I import ImageEditor from node modules, I'm getting the following error "Cannot find module 'react-image-editor' or its corresponding type declarations."

This project is not a package. It's a project on it's own, which means that it's not optimized for install and import to another project.

But I'm considering create a package which contains features in this project so that others can install, import and use those.

**Comment by swimmingkiim** [comment]
Closing this issue.
