### ISSUE TITLE
Node version issue.

### ISSUE THREAD

**Issue by mars9541** [swimmingkiim/react-image-editor#4]
Hi, @swimmingkiim 

Can you tell me what node version using?

I tried to run this on Node 16.16.0 and 18.16.0, but doesn't works. 

:) Please reply.

**Comment by swimmingkiim** [comment]
Sorry for late response.
I ran this project in node version 18.16.0 and it's working.
Have you solved this problem?

**Comment by mars9541** [comment]
> 

Yeah. it's working. Thank you.
