### ISSUE TITLE
Add text feature.

### ISSUE THREAD

**Issue by mars9541** [swimmingkiim/react-image-editor#5]
There is a Font tab, but user can't input their custom text.

**Comment by swimmingkiim** [comment]
Here is a simple video example of how to edit text.
After you drag and drop the text, click once for moving, click twice for editing the text content.
Before you click twice, make sure you unselect any object including the text itself.


https://github.com/swimmingkiim/react-image-editor/assets/54804279/e336716a-e783-4d3a-87b2-4a9809748208

**Comment by mars9541** [comment]
Thank you. You are a awesome.
