### ISSUE TITLE
Drag and Drop Images

### ISSUE THREAD

**Issue by mars9541** [swimmingkiim/react-image-editor#6]
What do you think of if it use OpenAI image generator insteadd of simple drag and drop?

I am sure it will be best.

**Comment by swimmingkiim** [comment]
Interesting. Open AI Image generator feature could be a new feature maybe! Since people use a lots of AI generated images now.

**Comment by smyja** [comment]
> What do you think of if it use OpenAI image generator insteadd of simple drag and drop?
> 
> I am sure it will be best.

I updated it. Check https://github.com/Smyja/mirage
